### ISSUE TITLE
Put documentation site up on develop

### ISSUE THREAD

**Issue by pixelyunicorn** [TULiberalArts/TUTheme-Documentation#1]
I would like to have a site up on http://develop.cla.temple.edu/docs/ so I can write documentation for tutheme-related setup and components.

**Comment by tu-chill** [comment]
@lidopaglia help...

**Comment by lidopaglia** [comment]
we can certainly alias this on develop. I just need to know what to proxy it to. Rather than building an entire jekyll site for this documentation what about using the wiki feature of github or something like [read the docs](http://docs.readthedocs.io/en/latest/getting_started.html)?

**Comment by pixelyunicorn** [comment]
I'll put the documentation in the GitHub TUTheme wiki instead (for now)

**Comment by tu-chill** [comment]
![screen shot 2017-05-01 at 10 58 17 am](https://cloud.githubusercontent.com/assets/12816361/25582831/210b8ab6-2e5d-11e7-88f2-b5d762265ffd.png)

@LabLayers I don't think the wiki has anything in it...
